services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports: 
      - 443:443
    tmpfs:
      - /tmp
  rust:
    build:
      context: .
      dockerfile: Dockerfile-rust
    expose:
      - 3000