log_format json escape=json '{ "timestamp": "$time_iso8601", '
     '"id": "$request_id", '
     '"address": "$remote_addr", '
     '"method": "$request_method", '
     '"uri": "$request_uri", '
     '"host": "$host", '
     '"statusCode": $status, '
     '"bodyBytes": $body_bytes_sent, '
     '"timer": $request_time, '
     '"referrer": "$http_referer", '
     '"xForwardFor": "$http_x_forwarded_for", '
     '"userAgent": "$http_user_agent" }';
 
server {
    # listen 443 ssl;
    listen 8080;
    server_tokens off;

    access_log /var/log/nginx/access.log json;

    ssl_certificate /etc/nginx/conf.d/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/conf.d/ssl/key.pem;

    gzip on;
    gzip_comp_level 4;
    gzip_types text/css application/json application/javascript text/javascript application/wasm;
    gzip_proxied any;

    if ($http_x_forwarded_proto = "http") {
        rewrite ^(.)$ https://$host$1/ permanent;
    }

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains;";

    
    location /api/ {
        expires epoch;
        proxy_pass http://rust:3000;
        proxy_pass_header Server;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Request-Id $request_id;

        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
    }

    location /pkg {
        expires max;
        alias /work/site/pkg;
    }

    # Serve public files (robots.txt, favicon.ico, sitemap.xml, etc.)
    location ~ ^/(robots.txt|favicon.ico|sitemap.xml)$ {
        alias /work/site/;
        try_files $uri =404;
        expires 1d;
        add_header Cache-Control "public, no-transform";
    }


    location / {
        proxy_pass http://rust:3000;
    }
}